name = "ens-gateway"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB"
database_name = "rcu"
database_id = "90f70333-4ae2-4595-ae89-07f2a876dae8"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
